services:
  backend:
    build:
      context: .
      dockerfile: deploy/backend.containerfile
      target: runner-dev
    restart: always
    develop:
      watch:
        - path: ./backend/
          target: /usr/src/
          action: sync
          ignore:
            - requirements.txt
        - path: ./backend/requirements.txt
          target: /usr/src/requirements.txt
          action: rebuild
    volumes:
      - ./.data/backend:/data
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: deploy/frontend.containerfile
      target: runner-dev
    restart: always
    develop:
      watch:
        - path: ./frontend/
          target: /usr/src/
          action: sync
          ignore:
            - package-lock.json
        - path: ./frontend/package.json
          target: /usr/src/package.json
          action: sync+restart
        - path: ./frontend/package-lock.json
          target: /usr/src/package-lock.json
          action: rebuild
    ports:
      - "3000:3000"

  fuseki:
    image: stain/jena-fuseki:latest
    container_name: jena-fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./databases:/fuseki/databases
      - ./config:/fuseki/configuration
    environment:
      - ADMIN_PASSWORD=smartcity-kb
    restart: always
