services:
  backend:
    build:
      context: backend
      target: runner-dev
    restart: always
    volumes:
      - ./.data/backend:/data
      - ./backend/app/:/app/app/
      - ./backend/.env:/app/.env
    ports:
      - "5000:5000"
  frontend:
    build:
      context: frontend
      target: runner-dev
    restart: always
    volumes:
      - ./frontend/app:/app/app/
      - ./frontend/public:/app/public/
      - ./frontend/.env:/app/.env
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
    ports:
      - "3000:3000"
