services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: 5000
    restart: always
    volumes:
      - ./.data/website:/data
      - ./app/:/app/app/
    ports:
      - "5000:5000"
    env_file:
      - .env
